# 开发环境

spring:
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sport?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456


  resources:
    # 配置静态资源路径
    static-locations: classpath:/templates/,classpath:/static/
  chain:
    strategy:
    content:
        enabled: true
        paths: /**
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.fengwenyi.mp3demo.model
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    #启动结果集自动映射
    auto-mapping-behavior: partial
    #驼峰映射   多数据源时，必须使用自定义配置，比如使用配置类来实现
    map-underscore-to-camel-case: true

mybatis:
  # mybatis 控制台输出sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置.xml文件路径
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.sports.entity

# 密码MD5加密盐值
password:
  salt: geelysdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,


# 上传到远程阿里云OSS配置
#aliyun:
#  oss:
#    file:
#      # bucket可以在控制台创建，也可以使用java代码创建
#      bucketname: sport-image-manage
#      # 不同的服务器地址不同
#      endpoint: oss-cn-beijing.aliyuncs.com
#      keyid: LTAI4GCFeP6gnz7Ru4Z4tuSa
#      keysecret: iMg6aNpSrtpQMyeV1sD83GF0I5PbTP

oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  url: https://sport-image-manage.oss-cn-beijing.aliyuncs.com/
  accessKeyId: LTAI4GCFeP6gnz7Ru4Z4tuSa
  accessKeySecret: iMg6aNpSrtpQMyeV1sD83GF0I5PbTP
  bucketName: sport-image-manage
