server:
  port: 8088
  tomcat:
    max-swallow-size: 500MB
spring:
  profiles:
    active: dev



  salt: geelysdafaqj23ou89ZXcj@#$@#$#@KJdjklj;D../dSF.,
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
      resolve-lazily: true

